### PR TITLE
Add external link for slate block(#22)

### PR DESCRIPTION
**Pull request by iRohitSingh**
Screenshot 2023-08-01 at 16 48 26

### CODE REVIEW

**Review by iFlameing — APPROVED** [review]
LGTM!

**Comment by danalvrz** [comment]
> LGTM!

@iFlameing if possible, please let me know about changes before merging so at least a couple people get the chance to take a look.

**Comment by davisagli** [comment]
@iFlameing The problem with this solution (using the CSS selectors based on the `href` attribute) is that we have to keep reimplementing the same CSS for each project, with a different URL.

Instead, we could add a feature to the UniversalLink component in volto to add an "external" class to external links. Then we could include CSS in volto-light-theme for `.external` and it would be the same CSS for every project. UniversalLink already checks if the link is external, so it should not be hard to implement. What do you think?

/cc @sneridagh @danalvrz

**Comment by sneridagh** [comment]
@iFlameing @iRohitSingh @danalvrz @davisagli +1 for the implementation suggested by David. Still catching up, maybe you already implemented it!

**Comment by iFlameing** [comment]
@sneridagh Doing it right now.

**Pull request merged**
