### PR TITLE
Fix the URL to the sitemap as part of #423

### PR DESCRIPTION
**Pull request by stevepiercy**
No change log needed.

----
📚 Documentation preview 📚: https://volto-light-theme--429.org.readthedocs.build/

### CODE REVIEW

**Comment by stevepiercy** [comment]
If https://volto-light-theme--429.org.readthedocs.build/robots.txt contains the correct URL of `https://volto-light-theme.readthedocs.io/sitemap.xml` in RTD, then this passes.

**Comment by stevepiercy** [comment]
meh, nevermind, I forgot that RTD uses its own robots.txt, so we can't verify it until it merges and builds.

We'll need to look at:

https://volto-light-theme.readthedocs.io/robots.txt

**Comment by stevepiercy** [comment]
I'm just going to merge it, and see what happens.

**Comment by stevepiercy** [comment]
No I'm not, I lack sufficient permission. Up to you @sneridagh. lol.

**Comment by davisagli** [comment]
@stevepiercy I can't tell whether it deployed to RTD after merging or not.

**Comment by stevepiercy** [comment]
@davisagli it did https://volto-light-theme.readthedocs.io/robots.txt and it has the correct URL now:

```text
Sitemap: https://volto-light-theme.readthedocs.io/sitemap.xml
```

...which in turn resolves to the sitemap. You got SEO! Let the visits counter soar!

**Comment by davisagli** [comment]
@stevepiercy thanks!

**Pull request merged**
