### PR TITLE
Fix teaser styles on add form

### LINKED ISSUE #354: Teaser Grid Block shows left/right margin when adding a new block
# StR

- as admin
- go to https://light-theme.kitconcept.io/add?type=Document
- add a new grid block with three columns
- choose "Teaser" subblock for the first column
- choose "Content Type" -> "Page" as a target
- -> Problem: teaser shows a big margin on the left/right side

# URL

https://light-theme.kitconcept.io/add?type=Document

# Screenshot

Add-Document (6)

### PR DESCRIPTION
**Pull request by davisagli**
Fixes #354 

Screenshot 2024-03-03 at 12 46 01 PM

### CODE REVIEW

**Review by tisto — APPROVED** [review]

**Review by tisto — APPROVED** [review]
LGTM! Thank you David!!!

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@davisagli thanks David for taking care!

**Comment by tisto** [comment]
@sneridagh can we make a release tomorrow? Then I can create my screencast tomorrow evening...my keynote will be the day after tomorrow...

**Comment by sneridagh** [comment]
@tisto no need for a release, it's there already:

image

**Comment by sneridagh** [comment]
I will make a release tomorrow though and make a final general review.

**Comment by sneridagh** [comment]
released.

**Pull request merged**
