### PR TITLE
Fix horizontalMenu of Toc block

### PR DESCRIPTION
**Pull request by iRohitSingh**
Screenshot 2023-07-19 at 18 22 57

### CODE REVIEW

**Comment by sneridagh** [comment]
@iRohitSingh do we have a mock for it? I can't remember.

**Comment by iRohitSingh** [comment]
@sneridagh We don't have mockup but it is looking awful. I made it like dlr.

Screenshot 2023-07-19 at 21 40 12

**Comment by davisagli** [comment]
@sneridagh You merged a fix for the same issue in volto a few days ago: https://github.com/plone/volto/pull/4912

**Comment by sneridagh** [comment]
That's why I'm asking!

**Comment by sneridagh** [comment]
@iRohitSingh update your build please, the fix should be in there already. But we still need a mock.

**Comment by iRohitSingh** [comment]
ok

**Pull request closed without merging**
