### PR TITLE
Allow customization the secondary navigation entries via Portal action

### PR DESCRIPTION
**Pull request by iFlameing**
@sneridagh screenshot for frontend implementation.

Screenshot 2023-12-27 at 7 16 19 PM

### CODE REVIEW

**Comment by iFlameing** [comment]
@sneridagh This is also done just need a proper way to merge  all the things which I worked on. https://github.com/kitconcept/kitconcept.voltolighttheme/pull/28

**Comment by sneridagh** [comment]
merged.

**Comment by iFlameing** [comment]
> @iFlameing can we have a cypress test for this?

absolutely. Will add it tomorrow morning.

**Comment by iFlameing** [comment]
@sneridagh When running the acceptance server, I am not getting my github link which I added. I think because we are using docker backend which doesn't contains my changes. By default contact is coming from site action pr and I added  the cypress for that.

**Pull request merged**
