### PR TITLE
Make Volto requirements more explicit.

### PR DESCRIPTION
**Pull request by fredvd**

### CODE REVIEW

**Comment by sneridagh** [comment]
@fredvd I don't think that we did nothing breaking that would make 4.x not work with Volto 17.

**Comment by fredvd** [comment]
I tried it in a 17 project by pinning 4.0.0 and it fails. Iirc something with not finding ‘@plone/components’.   That’s why I started looking for more info. I can give you the exact error if you  want to see it.

**Comment by sneridagh** [comment]
@fredvd uh, I see the problem now... I will fix it.

**Comment by sneridagh** [comment]
@fredvd now should be fine, can you test it using 4.0.1?
Now the dependencies are ok:

```
32  "dependencies": {
33    "@plone/components": "2.0.0-alpha.11"
34  },
```

**Comment by sneridagh** [comment]
@fredvd I added this https://github.com/kitconcept/volto-light-theme/pull/405/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R235 to the other PR, that will supersed this one.

**Comment by sneridagh** [comment]
@fredvd I confirmed that using 4.0.1 package it does work with Volto 17.
I am introducing a new requirement though, using #405 I will issue a new breaking in there to make it noticeable.

**Pull request closed without merging**
