### PR TITLE
Fix Introduction-Block inline-styles have wrong typography.

### PR DESCRIPTION
**Pull request by iFlameing**
@steffenri please review this.

### CODE REVIEW

**Comment by steffenri** [comment]
@iFlameing This will only increase font-size on lists. 
We also want all the other inline-styles to have 24px font-size: Links, italic.
I checked the other ones, they are fine.

**Comment by sneridagh** [comment]
@iFlameing  please move this one forward.

**Comment by iFlameing** [comment]
@sneridagh I think it is done. I checked everything and it works. I am going to merge master here.

**Comment by iFlameing** [comment]
@steffenri @sneridagh If you have time please merge this.

**Comment by iFlameing** [comment]
@steffenri can you please review and approve this pr.

**Comment by steffenri** [comment]
> @iFlameing This will only increase font-size on lists. We also want all the other inline-styles to have 24px font-size: Links, italic. I checked the other ones, they are fine.

@iFlameing Is this fixed?

**Comment by iFlameing** [comment]
@sneridagh Please review this also.

**Review by steffenri — APPROVED** [review]

**Pull request merged**
