### PR TITLE
Add Search icon is missing on tablet & mobile screen sizes

### LINKED ISSUE #266: Menu: Search icon/function is missing on tablet & mobile screen sizes
When the desktop navigation disappears from the header, the  search icon is also removed and search is no longer reachable.

( There is also an issue where no navigation is shown at all between viewport 977 - 1006. See #265 )

But after the hamburger re-appears on widths <= 977 there is still no search icon and the icon is also not embedded in the mobile nav menu as is the case in for example dlr.de

Screenshot 2023-11-19 at 16 48 03

### PR DESCRIPTION
**Pull request by iRohitSingh**
Fix #266

### CODE REVIEW

**Comment by iRohitSingh** [comment]
Mobile:

Screenshot 2023-12-18 at 4 43 02 PM

Tablet:

Screenshot 2023-12-18 at 4 44 11 PM

**Comment by iRohitSingh** [comment]
@steffenri We need to update the searchview to include a search input beacause currently we don't have for the search page. So even you click on the mobile icon search icon you are not able to search. Should I also implement that?

2. The icon for search figma has bottom line in left whereas in plone/volto/icon it is on right. @sneridagh always tell me to use plone/volto icon. That's why I used that one.

Also I am able to spot a text call 'Back' in mobile menu but it is not in figma. Should I also remove it or it is fine.
cc @sneridagh

**Comment by steffenri** [comment]
> @steffenri We need to update the searchview to include a search input beacause currently we don't have for the search page. So even you click on the mobile icon search icon you are not able to search. Should I also implement that?
> 
> 2. The icon for search figma has bottom line in left whereas in plone/volto/icon it is on right. @sneridagh always tell me to use plone/volto icon. That's why I used that one.
> 
> Also I am able to spot a text call 'Back' in mobile menu but it is not in figma. Should I also remove it or it is fine. cc @sneridagh

@iRohitSingh @sneridagh Can we not do it via a search view but with an input-field that redirects to the search in case people put a searchterm and press enter/push a button?
I think this is what we agreed on and this would align with the desktop implementation.

The icon is fine. No need to change that.

Where did you spot that text? Can you add a screenshot?

**Comment by iRohitSingh** [comment]
Back text 

Screenshot 2023-12-18 at 5 42 14 PM

**Comment by sneridagh** [comment]
@iRohitSingh  I agree with @steffenri, let's keep it as in DLR, where it's a link to the search page (in mobile).

Regarding the text, it's how it's in DLR as well, I think it's fine.

**Comment by sneridagh** [comment]
@iRohitSingh please move this one forward.

**Comment by iRohitSingh** [comment]
https://github.com/kitconcept/volto-light-theme/assets/61353484/0e527c89-3ab7-4f96-9490-5cb2352a0a60

**Comment by iRohitSingh** [comment]
@steffenri  Done , can you please review ?

https://github.com/kitconcept/volto-light-theme/assets/61353484/d06805df-2c94-446f-bca6-2addbb70e60d

**Review by steffenri — APPROVED** [review]

**Pull request merged**
