### PR TITLE
Add a11y tests infrastructure

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by iRohitSingh** [comment]
I Add A11y test and fix violation, the only thing is missing

1. Home page a11y test ( once this pr https://github.com/kitconcept/volto-light-theme/pull/288 merge the slider block a11y test is also fixed )
2. Accordion block a11y test (Error is thrown but it is totally unrelated. Not able to find the culprit.)
3. Same for table block. Both are giving exact error.

**Comment by sneridagh** [comment]
> @sneridagh I Add A11y test and fix violation, the only thing is missing
> 
> 1. Home page a11y test ( once this pr [Adapt new slider (6.0.0) in light theme #288](https://github.com/kitconcept/volto-light-theme/pull/288) merge the slider block a11y test is also fixed )
> 2. Accordion block a11y test (Error is thrown but it is totally unrelated. Not able to find the culprit.)
> 3. Same for table block. Both are giving exact error.
> 
> Screenshot of 'Error in Accordion block and table block'
> 


Ok, I will merge the slider PR. The error in the screenshot is related to the slider, not the accordion, right? I can see the classnames of it.

**Comment by iRohitSingh** [comment]
> > @sneridagh I Add A11y test and fix violation, the only thing is missing
> > 
> > 1. Home page a11y test ( once this pr [Adapt new slider (6.0.0) in light theme #288](https://github.com/kitconcept/volto-light-theme/pull/288) merge the slider block a11y test is also fixed )
> > 2. Accordion block a11y test (Error is thrown but it is totally unrelated. Not able to find the culprit.)
> > 3. Same for table block. Both are giving exact error.
> > 
> > Screenshot of 'Error in Accordion block and table block'
> 
> Ok, I will merge the slider PR. The error in the screenshot is related to the slider, not the accordion, right? I can see the classnames of it.

Yeah, I also think the same thing. I don't know from where it is leaking. I am unable to find the culprit that's why I mentioned it. After the slider pr merge I will try once again.

**Comment by sneridagh** [comment]
I just merged andd sync this branch.

**Comment by iRohitSingh** [comment]
@sneridagh I don't know how to fix this a11y error. sometimes it passes, sometimess it doesn't.

'Ensure that the page, or at least one of its frames contains a level-on headeing'

and also please deploy the new image of kitconceptvoltolighttheme. my changes are not available in docker image so maps block a11y is falling.



On ci text block passes but locally it fails screenshot

Screenshot 2023-12-27 at 9 32 58 PM

**Pull request merged**
